#pragma once

#include "structs.hpp"

EXTERN_C_START

	NTSYSAPI ERESOURCE PsLoadedModuleResource;
	NTSYSAPI POBJECT_TYPE* IoDriverObjectType;
	NTSYSAPI POBJECT_TYPE* IoDeviceObjectType;
	NTSYSAPI KLDR_DATA_TABLE_ENTRY* PsLoadedModuleList;

	NTSYSAPI NTSTATUS			NTAPI ZwQuerySystemInformation( SYSTEM_INFORMATION_CLASS, PVOID, ULONG, PULONG );
	NTSYSAPI PCHAR				NTAPI PsGetProcessImageFileName( PEPROCESS );
	NTSYSAPI ULONG_PTR			NTAPI PsGetProcessPeb( PEPROCESS );
	NTSYSAPI NTSTATUS			NTAPI MmCopyVirtualMemory( PEPROCESS, PVOID, PEPROCESS, PVOID, SIZE_T, KPROCESSOR_MODE, PSIZE_T );
	NTSYSAPI NTSTATUS			NTAPI ObReferenceObjectByName( UNICODE_STRING*, ULONG, PACCESS_STATE, ACCESS_MASK, POBJECT_TYPE, KPROCESSOR_MODE, PVOID, PVOID* );
	NTSYSAPI PVOID				NTAPI RtlFindExportedRoutineByName( PVOID, LPCSTR );
	NTSYSAPI PVOID				NTAPI PsGetProcessWow64Process( PEPROCESS );
	NTSYSAPI PIMAGE_NT_HEADERS	NTAPI RtlImageNtHeader( PVOID );
	NTSYSAPI NTSTATUS			NTAPI ZwProtectVirtualMemory( HANDLE, PVOID*, PSIZE_T, ULONG, PULONG );
	NTSYSAPI PVOID				NTAPI PsGetProcessSectionBaseAddress( PEPROCESS );
	NTSYSAPI ULONG				NTAPI KeCapturePersistentThreadState( PCONTEXT Context, PKTHREAD Thread, ULONG BugCheckCode, ULONG BugCheckParameter1, ULONG BugCheckParameter2, ULONG BugCheckParameter3, ULONG BugCheckParameter4, PVOID VirtualAddress );

EXTERN_C_END;